apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext974
  labels:
    app: BoundedContext974
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext974
  template:
    metadata:
      labels:
        app: BoundedContext974
    spec:
      containers:
        - name: BoundedContext974
          image: username/BoundedContext974:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
